[package]
name = "cargo-release-test"
version = "0.1.0"
edition = "2021"
description = "A cargo-release test"
license = "MIT"
documentation = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
